#+TITLE:     Clojure Box
#+AUTHOR:    Shawn Hoover
#+EMAIL:     shawn@bighugh.com
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t *:t TeX:t LaTeX:nil
#+OPTIONS:   author:nil creator:nil timestamp:nil
#+STYLE: <link rel="stylesheet" type="text/css" href="styles.css" />

Clojure Box is an all-in-one installer for [[http://clojure.org][Clojure]] on Windows.  It's inspired
by the [[http://gigamonkeys.com/book/lispbox][Lispbox]]: you simply install and run this one thing, and you get a [[http://clojure.org/dynamic][REPL]]
and all the syntax highlighting and editing goodies from clojure-mode and
Slime, plus all the power of Emacs under the hood.


* Requirements

All you need is Java 1.5 or later. If Clojure Box can find java.exe on your
system (usually it's in c:\windows\system32), it provides the rest.


* Download

Here's the box. See the [[file:release-log.org][release notes]] for more details.

[[file:releases/clojure-box-1.1RC1-2-setup.exe][BETA Clojure Box 1.1RC1]] published December 19, 2009, built from the official
Clojure 1.1RC1 download.

[[file:releases/clojure-box-1.0-setup.exe][Clojure Box 1.0]], published May 9, 2009, built with the official Clojure
1.0 release.

[[file:releases/clojure-box-20090320-setup.exe][Clojure Box 20090320]], published April 8, 2009, built with the official Clojure
20090320 release.

[[file:releases/clojure-box-r1235-setup.exe][Last release before lazier Clojure]], published February 1, 2009, matching
Clojure svn r1235. This release contains lazy-cons and lazy-seq, which [[http://clojure.org/lazier][lazier Clojure]] removed.

[[./releases][Older versions]]


* Components

Clojure Box consists of these components:

- [[http://clojure.org][Clojure]]
- [[http://sourceforge.net/projects/clojure-contrib/][Clojure Contrib]]
- [[http://ourcomments.org/Emacs/EmacsW32.html][Emacs, via EmacsW32]]
- [[http://github.com/technomancy/clojure-mode][clojure-mode]]
- [[http://github.com/technomancy/swank-clojure][swank-clojure]]
- [[http://common-lisp.net/project/slime/][Slime]]
- [[http://mumble.net/~campbell/emacs/paredit.el][Paredit]]

Thanks to all the developers of these excellent packages!


* Contact

The Clojure Box installer is maintained by Shawn Hoover. I [[mailto:shawn@bighugh.com][welcome comments]]
about the package.


#+BEGIN_HTML Google Analytics
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." :
"http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost +
"google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-11886472-1");
pageTracker._trackPageview();
} catch(err) {}</script>

<!-- styles.css thanks to Shane Eller -->
#+END_HTML
